GSoC butteraugli
rust-av/butteraugli-rs pull request #2
Opened 2021-08-29 17:16 UTC by sn99

What's done: 
- bindings
- few tests
- part conversion to pure rust

What's left:
- Own implementation of `Image` Struct
- Add changes made by libjxl to butteraulgi

Related blog entries:
- [Butteraugli: Google vs libjxl](https://sn99.github.io/2021/06/07/butteraugli-google-vs-libjxl/)
- [First week of GSoC](https://sn99.github.io/2021/06/15/first-week-of-gsoc/)
- [Ending: GSoC](https://sn99.github.io/2021/08/28/ending-gsoc/)

2021-08-29 17:52 UTC, lu-zero commented on Cargo.toml
> +name = "butteraugli-rs"
the crate name remains `butteraugli`. Please fix it.

2021-08-29 17:53 UTC, lu-zero commented on butteraugli-sys/.cargo/config
> +rustflags = ["-C", "link-args=-lpng -ljpeg"]
You should use [systemdeps](https://crates.io/crates/system-deps).

2021-08-30 06:48 UTC, lu-zero requested changes
Does the code at least build?

2021-08-30 10:52 UTC, lu-zero commented on src/image.rs
> +    pub ysize_: usize,
Remove the `_` at the end

2021-08-30 10:53 UTC, lu-zero commented on src/butteraugli.rs
> +    for y in 0..in_.ysize() {
this would be the `ysize` field.

2021-08-30 10:54 UTC, lu-zero commented on src/butteraugli.rs
> +        let row_in = in_.Row(y);
Look at how v_frame has `row()` and `rows_iter()` per-plane.

2021-08-30 10:55 UTC, lu-zero commented on src/butteraugli.rs
> +        row_out[y] = sum * scale;
row_out cannot be a f64, it looks like it is a slice

2021-08-30 14:57 UTC, sn99 commented
Forgot to commit our parts of Image, some functions are still a placeholder, bindings build fine

2021-08-30 15:28 UTC, lu-zero commented on .cargo/config
> +rustflags = ["-C", "link-args=-lpng -ljpeg"]
This is not the way to do it, I told you to use [system-deps](https://crates.io/crates/system-deps) ...

2021-08-30 15:36 UTC, sn99 commented on .cargo/config
> +rustflags = ["-C", "link-args=-lpng -ljpeg"]
I unresolved the previous one already, I was resolving another one and misclicked this one

2021-09-10 20:57 UTC, closed without merging